# Generated by Django 4.0.3 on 2022-03-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('pnumber', models.IntegerField()),
                ('college', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
