# Generated by Django 4.0.3 on 2022-03-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Applicants',
        ),
    ]
