# Generated by Django 4.0.1 on 2022-01-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='applicants',
        ),
    ]
